#!/bin/zsh
#zplug async
zplug hacker-quotes
zsh-defer zplug bd
zsh-defer zplug lazyload
zsh-defer zplug completions
zsh-defer zplug auto-notify
zsh-defer zplug systemd
#zsh-defer zplug autocomplete
zsh-defer zplug fast-syntax-highlighting
zsh-defer zplug autosuggestions
zsh-defer zplug autopair
zsh-defer zplug you-should-use
zsh-defer zplug bash-completions-fallback
zsh-defer zplug zshmarks
zsh-defer zplug history-substring-search
zsh-defer zplug command-time
#zplug auto-ls
zsh-defer zplug autoswitch_virtualenv
zsh-defer zplug rockz
zsh-defer zplug git-extra-commands
zsh-defer zplug zinsults

