#!/bin/zsh
# zplug async
ZSH_HACKER_QUOTES_ENABLE_WHEN_INTERACTIVE=1
zplug hacker-quotes
unset ZSH_HACKER_QUOTES_ENABLE_WHEN_INTERACTIVE
zplug bd
unalias .. ... ....
zplug lazyload
zplug completions
zplug auto-notify && {
	AUTO_NOTIFY_THRESHOLD=20
	AUTO_NOTIFY_EXPIRE_TIME=5000
	AUTO_NOTIFY_WHITELIST=()
	AUTO_NOTIFY_IGNORE+=(
		man info
		gcc g++ pbi wormhole
		shit danime git
		nano xed gedit vi vim
		vlc mpv celluloid
		yay pacman bc
	)
}
zplug systemd
zplug autopair
zplug autosuggestions && {
	ZSH_AUTOSUGGEST_STRATEGY=(history completion)
	ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
}
zplug fast-syntax-highlighting && {
	((${+aliases[fsh-alias]})) && \
	unalias fsh-alias
}
zplug you-should-use && {
	YSU_MESSAGE_POSITION=after
#	YSU_HARDCORE=1
	YSU_MESSAGE_FORMAT="$(print -P %B%F{cyan})Use \"$(print -P %F{blue})%alias$(print -P %F{cyan})\", $(print -P %F{red})you little shit!$(print -P %b%f)"
	function ysu:start { enable_you_should_use; }
	function ysu:stop { disable_you_should_use; }
	function ysu:stat {
		echo YSU Stats
		check_alias_usage 2>&1|grep -v 'entry='
	}
}
zplug bash-completions-fallback
zplug zshmarks && {
	alias jmp=jump
	alias mark=bookmark
	alias unmark=deletemark
	alias lsmark=showmarks
}
zplug history-substring-search && {
	bindkey "$terminfo[kcuu1]" history-substring-search-up
	bindkey "$terminfo[kcud1]" history-substring-search-down
}
zplug command-time && {
	ZSH_COMMAND_TIME_MSG="Execution time: %s"
	ZSH_COMMAND_TIME_COLOR=cyan
}
#zplug auto-ls
VIRTUAL_ENV_DISABLE_PROMPT=1
zplug autoswitch_virtualenv
zplug zinsults
zinsults_load=('default' 'shakespeare')

