#!/bin/bash -e
# HOOK-CONDITION: [ "$(git config --bool aur.hook.srcinfo)" != "false" ]
# HOOK-CONDITION: [[ $(git remote get-url origin) =~ ^ssh://aur@aur.archlinux.org/ ]]
if grep -q 'git://|git+http' PKGBUILD;then
	makepkg -o
fi
hook_print "Updating SRCINFO" info
makepkg --printsrcinfo > .SRCINFO
git add .SRCINFO
