#!/bin/bash -e
# HOOK-CONDITION: [[ $(git remote get-url origin) =~ ^ssh://aur@aur.archlinux.org/ ]]
IFS=$'\r\n' GLOBIGNORE='*' command eval 'STAGED=($(git diff --name-only --cached))'
git reset -q
if [ ! -f .gitignore ];then
	hook_print "Initializing gitignore"
	echo '*' >.gitignore
else
	hook_print "Updating gitignore"
fi
for n in "${STAGED[@]}";do
	grep -q "$n$" .gitignore && continue
	echo '!'"$n" >> .gitignore
done
grep '^!' .gitignore|cut -c2-|while read line;do
	if ! [ -e "$line" ];then
		sed -i "/^\!$line$/d" .gitignore
	fi
done
git add --force .gitignore
for n in "${STAGED[@]}";do
	git add --force "$n"
done
