#!/bin/bash
declare -A f
if tput setaf 0 &> /dev/null; then
	f[reset]="$(tput sgr0)"
	f[bold]="$(tput bold)"
	f[blue]="${f[bold]}$(tput setaf 4)"
	f[green]="${f[bold]}$(tput setaf 2)"
	f[red]="${f[bold]}$(tput setaf 1)"
	f[yellow]="${f[bold]}$(tput setaf 3)"
else
	f[reset]="\e[0m"
	f[bold]="\e[1m"
	f[blue]="${f[bold]}\e[34m"
	f[green]="${f[bold]}\e[32m"
	f[red]="${f[bold]}\e[31m"
	f[yellow]="${f[bold]}\e[33m"
fi
readonly f
