#!/bin/zsh
# function zcompinit
if [[ -o interactive ]];then
	compinit $@
	source ${ZDOTDIR:-$HOME/.zsh}/compdef
	[[ $* =~ -[[:alnum:]]*C ]] || {
		autoload -Uz zrecompile
		zrecompile
		compinit -C
		source ${ZDOTDIR:-$HOME/.zsh}/compdef
	}
fi
unfunction zcompinit
