#!/bin/zsh

autoload -Uz zcompare
local target dir file
for target in ${ZDOTDIR:-$HOME}/.z{shrc,shenv,login,logout,profile,inputrc} ${ZDOTDIR:-$HOME/.zsh}/{compdef,lazyload} $fpath[@]/^*.zwc;do
	if [[ -f $target ]] && [[ -w $target:P:h ]];then
		zcompare "$target" -Rz
	elif [[ -d $target ]] && [[ -w $target ]];then
		for dir in "$target" "$target"/**/*(/);do
			for file in "$dir"/^*(.(zwc|md|adoc|png|gif)|(LICENSE|CHANGELOG))(^/);do
				zcompare "$file" -R
			done
		done
	fi
done
for target in $HOME/.cache/zsh/compdump ~/.cache/zsh/compcache/^*.zwc;do
	zcompare "$target" -M
done
