#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

if [ -f ~/.shell/environment ]; then
	. ~/.shell/environment
fi
if [ -f "$HOME/.bashrc" ] && [ -n "$BASH_VERSION" ]; then
	. "$HOME/.bashrc"
fi

if [ -x ~/.shell/path.${SHELL##*/} ]; then
	export "PATH=$(~/.shell/path.${SHELL##*/})"
else
	append_path()
	{
		for n in "$@"; do
			case ":$PATH:" in
				*:"$n":*) ;;

				*)
					if [ -d "$n" ]; then
						${high:-false} && PATH="$n${PATH:+:$PATH}" || PATH="${PATH:+$PATH:}$n"
					fi
					;;
			esac
		done
	}
	high=true append_path "$HOME/bin"
	high=true append_path "$HOME/.go/bin"
	high=true append_path "$HOME/.local/bin"
	unset -f append_path
	for n in $(echo $PATH | tr ':' '\n'); do
		case ":$P:" in
			*:"$n":*) continue ;;
			*)
				if [ -d "$n" ]; then
					P="${P:+$P:}$n"
				fi
				;;
		esac
	done
	export PATH=$P
	unset P high
fi
PROXY=socks4://37.57.3.244:1080
