#!/bin/sh
if [ -f ~/.shell/environment ]; then
	. ~/.shell/environment
fi

services="ibus picom"
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
#ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
export XSECURELOCK_DATETIME_FORMAT="%A, %B %d, %Y %l:%M %P"
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_SAVER=$HOME/.local/lib/xsecbg.sh
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_BLANK_DPMS_STATE=off
export XSECURELOCK_FONT="Hack:style=Regular"
export XSECURELOCK_AUTHPROTO=authproto_htpasswd
export XSECURELOCK_PASSWORD_PROMPT=disco

dbus-update-activation-environment --all --systemd
systemctl --user --quiet start xorg.target
#xset +dpms
#xset s blank
if [ "$XDG_SESSION_DESKTOP" = "plasma" ]; then
	unset QT_AUTO_SCREEN_SCALE_FACTOR QT_SCALE_FACTOR QT_QPA_PLATFORMTHEME
	systemctl --user --quiet is-enabled deadd-notification-center.service &&
		systemctl --user stop deadd
else
	for service in $services; do
		systemctl --user restart "$service@$DISPLAY"
	done
	systemctl --user --quiet is-enabled deadd-notification-center.service &&
		systemctl --user restart deadd
fi
