# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null nano
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    cpr: pr create
    fork: repo fork --remote --org ahm-forks
    clone: repo clone
    create: repo create --public
prompt: enabled
