#!/bin/bash
if [ -f ~/.shell/environment ]; then
. ~/.shell/environment
fi
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
#ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
export XSECURELOCK_DATETIME_FORMAT="%A, %B %d, %Y %l:%M %P"
export XSECURELOCK_BLANK_DPMS_STATE=off
export XSECURELOCK_FONT="Hack:style=Regular"
export XSECURELOCK_AUTHPROTO=authproto_htpasswd
while read line; do
    export "$line"
done <<<$(bash -ic 'env' 2>/dev/null)
#xset +dpms
#xset s blank
systemctl --user restart ibus.slice
dbus-update-activation-environment --systemd --all
numlockx on
