#!/bin/bash
if [ -f ~/.shell/environment ]; then
	. ~/.shell/environment
fi
services=(
	ibus
	picom
	xfwm4
	xfce4-panel
	stalonetray
)
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
#ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
export XSECURELOCK_DATETIME_FORMAT="%A, %B %d, %Y %l:%M %P"
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_SAVER=$HOME/.local/lib/xsecbg.sh
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_BLANK_DPMS_STATE=off
export XSECURELOCK_FONT="Hack:style=Regular"
export XSECURELOCK_AUTHPROTO=authproto_htpasswd
export XSECURELOCK_PASSWORD_PROMPT=disco
while read line; do
	export "$line"
done <<< $(bash -c 'env' 2> /dev/null)

if [ -x ~/.shell/path.${SHELL##*/} ]; then
	export "PATH=$(~/.shell/path.${SHELL##*/})"
fi

dbus-update-activation-environment --all --systemd
#xset +dpms
#xset s blank
for service in "${services[@]}"; do
	systemctl --user restart "${service}@${DISPLAY}"
done
