#!/bin/bash
PATHSEP=:
shopt -s nullglob
cd "$(dirname "$(realpath "$0")")"
if realpath "$0"|grep -q "^$HOME" && [[ $1 = ln ]];then
	## non hidden dirs
	for n in bin;do
		echo Soft linking $n
		if [ ! -L "$HOME/$n" ];then
			rm -rf "$HOME/$n"
		fi
		ln -Tfs  "$PWD/$n" "$HOME/$n"
	done
	for n in dot-*;do
		s="$(realpath "$n")"
		t="${n#dot-}";t="${t//$PATHSEP//}"
		if [ -f "${s##*/}" ] && [ ! -L "$n" ];then
			echo Hard linking "$t"
			ln -f "$s" "$HOME/.$t"
		else
			echo Soft linking "$t"
			if [ ! -L "$HOME/.$t" ];then
				rm -fr "$HOME/.$t"
			fi
			if [ -L "$n" ];then
				s=$(realpath --relative-to="$(dirname "$HOME/.$t")" "$s")
			fi
			ln -Tfs  "$s" "$HOME/.$t"
		fi
	done
elif [[ $PWD == $(dirname "$(realpath "$0")") ]] && [[ $1 = ps ]] && [[ $2 =~ ^[[:punct:]]$ ]];then
	sed -i 's/^PATHSEP=.*$/PATHSEP='$2'/' $0
	for n in *;do
		if [[ $n != ${n//$PATHSEP/$2} ]];then
			echo "$n -> ${n//$PATHSEP/$2}"
			mv "$n" "${n//$PATHSEP/$2}"
		fi
	done
elif [[ $PWD == $(dirname "$(realpath "$0")") ]] && [[ $1 = rm ]];then
	shift
	[[ $1 =~ ^(-f|--force)$ ]] && shift && FORCE=true
	for n in "$@";do
		if [[ $n = ${0##*/} ]];then
			echo Can\'t remove dotfiles manager >&2
		elif [ -e "$n" ];then
			${FORCE:-false} || for p in 'Delete' 'Really delete' 'Really really delete';do
				unset REPLY;until [[ $REPLY =~ [YyNn$'\n'] ]];do
					read -i y -N 1 -rp"$p $n"'? [y/N]:'
					case "$REPLY" in
						(n|N|$'\n')	[[ "$REPLY" != $'\n' ]] && echo;continue 3;;
						(y|Y)		[[ $p != 'Really really delete' ]] && {
										printf '\r'
										tput el
									} || echo;;
						(*)			printf '\r';tput el;;
					esac
				done
			done
			echo Deleting $t
			t="${n#dot-}";t="${t//$PATHSEP//}"
			if [ ! -L "$HOME/.$t" ];then
				rm -fr "$HOME/.$t"
			else
				rm -f "$HOME/.$t"
			fi
			rm -rf $n
		else
			echo \'$n\' doesn\'t exist >&2
		fi
	done
elif [[ $PWD == $(dirname "$(realpath "$0")") ]] && [[ $1 = cp ]];then
	shift
	dotdir="$PWD"
	cd "$OLDPWD"
	for n in "$@";do
		if [ -L "$n" ] && readlink "$n"|grep -q "^$dotdir";then
			echo Already tracking \'$n\' >&2
			continue
		fi
		p="$(realpath --no-symlinks "$n")"
		if echo "$p"|grep -q "^$HOME/" ;then
			t="$(echo $n|sed 's@'$HOME'/@@;s@^\.@dot-@;s@/@'$PATHSEP'@g')"
			if [ -d "$n" ] && [ ! -L "$n" ];then
				cp -r "$n" "$dotdir/$t"
				rm -r "$n"
				ln -s "$dotdir/$t" "$n"
			elif [ -L "$n" ] && [ ! -d "$(realpath "$n")" ] && [ ! -f "$(realpath "$n")" ];then
				ln -fs "$(realpath "$n")" "$dotdir/$t"
				rm "$n"
				ln -s "$(realpath "$dotdir/$t")" "$n"
			elif realpath "$n"|grep -q "^$HOME/" && [ -L "$n" ];then
				if [ -f "$dotdir/$(readlink "$n"|sed 's@'$HOME'/@@;s@^\.@dot-@;s@/@'$PATHSEP'@g')" ];then
					n="$(readlink "$n"|sed 's@'$HOME'/@@;s@^\.@dot-@;s@/@'$PATHSEP'@g')"
				else
					n="$(realpath "$n")"
				fi
				ln -fs "$n" "$dotdir/$t"
			elif realpath "$n"|grep -q "^$HOME/" && [ -f "$n" ];then
				ln "$n" "$dotdir/$t"
			fi
		else
			echo $n is niether under '$HOME' nor a symlink. >&2
		fi
	done
elif [[ $1 = ls ]];then
	if [[ -n $(env which columns 2>/dev/null) ]];then
		cmd=columns
	elif [[ -n $(env which column 2>/dev/null) ]];then
		cmd='column -x'
	else
		cmd=cat
	fi
	find -maxdepth 1 -name 'dot-*' -print|cut -d/ -f2|eval "$cmd"
elif (($#==0))||[[ $1 = help ]];then
	(
		exec >&2
		echo "${0##*/} help:"
		echo "   ln         link dotfiles."
		echo "   ls         list dotfiles."
		echo "   ps [chr]   use chr as seperator."
		echo "   cp [path]  track path."
		echo "   rm [dot]   unlink and delete dotfile."
		echo "   help       show this help."
	)
else
	echo This repo should reside under \'$HOME\'
	exit 1
fi
