#!/bin/sh
cd "$(dirname "$0")"
if realpath "$0"|grep -q "^$HOME";then
	for n in dot-*;do
		if [ -f "$n" ];then
			echo Hard linking "${n//dot-/}"
			ln -f "$n" "$HOME/${n//dot-/.}"
		else
			echo Soft linking "${n//dot-/}"
			ln -Tfs  "$(realpath "$n")" "$HOME/${n//dot-/.}"
		fi
	done
else
	echo This repo should reside under \'$HOME\'
	exit 1
fi
