#!/bin/bash
# shellcheck disable=SC1090,SC2139
# shellcheck disable=SC2142
if [ -e ~/bin/libbash ]; then
	. ~/bin/libbash
fi
if [ -e ~/.weeb/aliases.sh ]; then
	. ~/.config/shell/weeb/aliases.sh
fi

# Specific aliases
for __alias_def__ in ~/.config/shell/aliases.d/*.sh; do
	__alias_def__="${__alias_def__%.sh}"
	command -v "${__alias_def__##*/}" 1>&3 2>&1 || continue
	source "${__alias_def__}.sh"
done
unset __alias_def__

#aliases
alias gist='gist -sc --skip-empty'
alias q="exit"
alias c="clear"
alias t=time
alias k="kill"
alias yt-dl="youtube-dl --xattrs --add-metadata --restrict-filenames -ir 1M -o '%(title)s.%(height)sp.%(ext)s' -R 10 -c "
alias yt-mp3="youtube-dl --restrict-filenames --xattrs --add-metadata --audio-format best -ir 1M -R 10 -x -o '%(title)s.%(ext)s' --audio-format mp3 --embed-thumbnail --convert-subs lrc -c"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sign='gpg --detach-sign'
alias clearsign='gpg --clearsign'
alias failunlock='faillock --reset --user $USER'
alias tree='tree --dirsfirst'
alias prime='env DRI_PRIME=1'
alias pytrace='python -m trace --trace --ignore-dir /usr --ignore-dir "$HOME/.local"'
alias mprime='mprime -s'
alias sudo='sudo -H'
alias spider='curl -ILksXGET'
alias dd='dd status=progress'
alias dbx=distrobox

# wormhole
if [ -x /usr/bin/wormhole ]; then
	alias send='wormhole send'
	alias recv='wormhole receive'
elif [ -x /usr/bin/wormhole-william ]; then
	alias send='wormhole-william send'
	alias recv='wormhole-william recv'
fi
# xfce4-pane-backup
if command -v xfce4-panel-profiles 2>&3 1>&2; then
	alias panbackup='xfce4-panel-profiles save "$XDG_DATA_HOME"/xfce4-panel-profiles/Default.tar.bz2'
	alias panload='xfce4-panel-profiles load "$XDG_DATA_HOME"/xfce4-panel-profiles/Default.tar.bz2'
fi
# exa
if [ "${TERM%-*}" = "xterm" ] && command -v exa 2>&3 1>&2; then
	alias ls=exa
	alias l='exa -F'
	alias tree='exa -T'
fi
# tldr
if hash tldr 1>&3 2>&1; then
	alias '?'=tldr
	alias h=tldr
	alias run-help=tldr
fi
# x11 alias
if [ -z "$XAUTHORITY" ]; then
	alias minimize='xdotool getactivewindow windowminimize;chvt 7'
fi
if [ -x /usr/bin/yay ]; then
	alias add='yay -S --needed'
	alias del='yay -Rcsn'
fi
if [ -x /usr/bin/time ]; then
	alias time="/usr/bin/time"
fi
if [ -x /usr/bin/ytfzf ]; then
	case $TERM in
		*-kitty) alias ytfzf="ytfzf -ft --thumb-viewer=kitty" ;;
		*) alias ytfzf="ytfzf -ft --thumb-viewer=chafa" ;;
	esac
fi
if [ -x /usr/bin/dog ]; then
	alias dig="/usr/bin/dog"
fi
if [ -x /usr/bin/makechrootpkg ]; then
	alias makechrootpkg="sudo makechrootpkg -ucnr /var/lib/archbuild"
fi

# Zsh suffix aliases
if [ -n "${ZSH_VERSION}" ] && [ -n "${ZSH_NAME}" ]; then
	alias -s tmate=ssh
	alias -s {txt,md}='less'
	alias -s {c,cpp,h,hpp,cxx,cc,hh}='nano'
	alias -s html='lynx'
	alias -s json="function {
		[ -z \"\$1\" ] && return
		[ -x /usr/bin/jiq ] && jiq < \"\$1\" || {
			jq -C '.' \"\$@\"|less
		}
	}"
fi
