#!/bin/sh
add_java_option()
{
	case "$JAVA_TOOL_OPTIONS" in
		*"-D$1"*) ;;
		*) JAVA_TOOL_OPTIONS="-D$1${JAVA_TOOL_OPTIONS+ $JAVA_TOOL_OPTIONS}" ;;
	esac
	export JAVA_TOOL_OPTIONS
}

for env__e in ~/.config/shell/env.d/*.sh; do
	. "$env__e"
done

unset env__e
unset -f add_java_option
