#!/bin/sh
# FD 3w /dev/null
exec 3> /dev/null

. "$XDG_CONFIG_HOME/shell/functions"
. "$XDG_CONFIG_HOME/shell/aliases"

tty -s || return
! test "${_SHELL_LINUS_FINGER_SHOWN}" = "in-$TERM" || return

if hash kitten 2> /dev/null && {
	[ "${TERM#xterm*-}" = "kitty" ] || [ "${TERM%[-+]*}" = "kitty" ]
}; then
	kitten icat --align=left "$XDG_CONFIG_HOME/shell/motd.png"
elif
	[ "${TERM_PROGRAM}" = "WezTerm" ] && hash wezterm 2> /dev/null
then
	wezterm imgcat "$XDG_CONFIG_HOME/shell/motd.png"
else
	cat "$XDG_CONFIG_HOME/shell/motd.txt" >&2
fi

export _SHELL_LINUS_FINGER_SHOWN="in-$TERM"
# vim: ft=sh
