#!/bin/zsh
path=(
	~/.local/bin
	~/bin
	"${XDG_DATA_HOME:-$HOME/.local/share}/go/bin"
	"${XDG_DATA_HOME:-$HOME/.local/share}/cargo/bin"
	$path
	/usr/lib/surfraw
	"${XDG_CONFIG_HOME:-$HOME/.config}/git/helpers"
	"${XDG_CONFIG_HOME:-$HOME/.config}/git/helpers/extras/bin"
)
_path=()
for each in $path;do
	printf '%s\n' $_path|grep -qxF "$each" && continue
	_path+=("$each")
done
path=($_path)
unset _path
