#!/bin/bash
if [ -e ~/bin/libbash ];then
	source ~/bin/libbash
fi
if [ -e ~/.weeb/aliases.sh ];then
	source ~/.weeb/aliases.sh
fi
if [ -x /usr/bin/thefuck ];then
	alias shit='fuck'
fi
#aliases
exec 3>/dev/null
if hash apt 1>&3 2>&1;then
	alias apt-i="apt install"
	alias আপ্ত='apt'
	alias apt-r="apt remove"
	alias apt-ri="apt reinstall"
	alias apt-fu="apt full-upgrade"
	alias apt-du="apt dist-upgrade"
	alias apt-uu="apt upgrade"
	alias apt-u="apt update"
fi
alias fixhist="sed -i '/[[:print:]]/!d' ~/.$0_history"
alias cls="rm -f ~/.bash_history"
alias err="echo -e \"$1\" &> /dev/stderr"
alias gist='gist -sc --skip-empty'
alias q="exit"
alias c="clear"
alias add='yay -S --needed'
alias del='yay -Rcsn'
if [ -x /usr/bin/time ];then
	alias time="/usr/bin/time"
fi
alias t=time
alias k="kill"
alias yt-dl="youtube-dl --xattrs --add-metadata --restrict-filenames -ir 1M -o '%(title)s.%(height)sp.%(ext)s' -R 10 -c "
alias yt-mp3="youtube-dl --restrict-filenames --xattrs --add-metadata --audio-format best -ir 1M -R 10 -x -o '%(title)s.%(ext)s' --audio-format mp3 --embed-thumbnail --convert-subs lrc -c"
if hash tldr 1>&3 2>&1;then
	alias '?'=tldr
	alias h=tldr
	alias run-help=tldr
fi
alias userctl='systemctl --user'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
if hash gcp 1>&3 2>&1;then
	alias cp='gcp'
fi
alias panbackup='xfpanel-switch save $HOME/.local/share/xfpanel-switch/Default.tar.bz2'
alias panload='xfpanel-switch load $HOME/.local/share/xfpanel-switch/Default.tar.bz2'
alias tree='tree --dirsfirst'
alias prime='env DRI_PRIME=1'
if [ -x /usr/bin/wormhole ];then
	alias send='wormhole send'
 	alias recv='wormhole receive'
elif [ -x /usr/bin/wormhole-william ];then
	alias send='wormhole-william send'
	alias recv='wormhole-william recv'
fi
alias mprime='mprime -s'
if hash hub 2>/dev/null;then
	alias git=hub
fi
alias sudo='sudo -H'
alias commit='git commit'
alias clone='git clone'
alias push='[[ $(git config "branch.$(git rev-parse --abbrev-ref HEAD).merge") = "" ]] && git push --all -u || git push --all'
alias tag='git tag -s'
alias spider='curl -ILksXGET'
### Colored Output

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='grep -E --color=auto'
