#!/bin/bash
# shellcheck disable=SC1090,SC2139
# shellcheck disable=SC2142
if [ -e ~/bin/libbash ]; then
	. ~/bin/libbash
fi
if [ -e ~/.weeb/aliases.sh ]; then
	. ~/.weeb/aliases.sh
fi
#aliases
exec 3> /dev/null
if hash apt 1>&3 2>&1; then
	alias apt-i="apt install"
	alias আপ্ত='apt'
	alias apt-r="apt remove"
	alias apt-ri="apt reinstall"
	alias apt-fu="apt full-upgrade"
	alias apt-du="apt dist-upgrade"
	alias apt-uu="apt upgrade"
	alias apt-u="apt update"
fi
alias cls="rm -f ~/.bash_history"
alias gist='gist -sc --skip-empty'
alias q="exit"
alias c="clear"
if [ -x /usr/bin/yay ]; then
	alias add='yay -S --needed'
	alias del='yay -Rcsn'
fi
if [ -x /usr/bin/time ]; then
	alias time="/usr/bin/time"
fi
if [ -x /usr/bin/dog ]; then
	alias dig="/usr/bin/dog"
fi
alias t=time
alias k="kill"
alias yt-dl="youtube-dl --xattrs --add-metadata --restrict-filenames -ir 1M -o '%(title)s.%(height)sp.%(ext)s' -R 10 -c "
alias yt-mp3="youtube-dl --restrict-filenames --xattrs --add-metadata --audio-format best -ir 1M -R 10 -x -o '%(title)s.%(ext)s' --audio-format mp3 --embed-thumbnail --convert-subs lrc -c"
if hash tldr 1>&3 2>&1; then
	alias '?'=tldr
	alias h=tldr
	alias run-help=tldr
fi
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias sign='gpg --detach-sign'
alias clearsign='gpg --clearsign'
alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
if hash gcp 1>&3 2>&1; then
	alias cp='gcp'
fi
alias failunlock='faillock --reset --user $USER'
alias panbackup='xfce4-panel-profiles save $HOME/.local/share/xfce4-panel-profiles/Default.tar.bz2'
alias panload='xfce4-panel-profiles load $HOME/.local/share/xfce4-panel-profiles/Default.tar.bz2'
alias tree='tree --dirsfirst'
alias prime='env DRI_PRIME=1'
if [ -x /usr/bin/wormhole ]; then
	alias send='wormhole send'
	alias recv='wormhole receive'
elif [ -x /usr/bin/wormhole-william ]; then
	alias send='wormhole-william send'
	alias recv='wormhole-william recv'
fi
alias pytrace='python -m trace --trace --ignore-dir /usr --ignore-dir '$HOME'/.local'
alias mprime='mprime -s'
if hash git 2> /dev/null; then
	for n in g gut giy hut; do
		alias "$n=git"
	done
	alias commit='git commit'
	alias pull='git pull'
	alias clone='git clone'
fi
alias sudo='sudo -H'
alias spider='curl -ILksXGET'
alias dd='dd status=progress'
### Colored Output

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='grep -E --color=auto'
if [ -z "$XAUTHORITY" ]; then
	alias minimize='xdotool getactivewindow windowminimize;chvt 7'
fi
# Zsh suffix aliases
if [ -n "${ZSH_VERSION}" ] && [ -n "${ZSH_NAME}" ]; then
	alias -s tmate=ssh
	alias -s {txt,md}='less'
	alias -s {c,cpp,h,hpp,cxx,cc,hh}='nano'
	alias -s html='lynx'
	alias -s json="function {
		[ -z \"\$1\" ] && return
		[ -x /usr/bin/jiq ] && jiq < \"\$1\" || {
			jq -C '.' \"\$@\"|less
		}
	}"
fi
