#!/bin/bash
# [Gedit Tool]
# Languages=cpp
# Output=output-panel
# Shortcut=<Primary><Shift>F1
# Applicability=titled
# Input=nothing
# Name=Show Binary
# Save-files=document

dext=${GEDIT_CURRENT_DOCUMENT_NAME##*.}
n=$(echo $GEDIT_CURRENT_DOCUMENT_NAME | sed -e s/.${dext}$//)
exo-open --launch TerminalEmulator "bash -c \"readelf --headers --syms --notes --use-dynamic --version-info --dynamic --unwind --relocs  z.$n.amd64.elf;read -rsp 'Press enter to continue'\""
