#!/bin/bash
# [Gedit Tool]
# Shortcut=<Shift>F1
# Name=Compile
# Languages=pascal
# Output=output-panel
# Input=nothing
# Applicability=titled
# Save-files=document

dext=${GEDIT_CURRENT_DOCUMENT_NAME##*.}
case $dext in
 [p,P][a,A][s,S])compiler=fpc;lang=Pascal;name=`echo $GEDIT_CURRENT_DOCUMENT_NAME | sed -e s/.[p,P][a,A][s,S]$// `;;
 *) cc=fpc;;
esac
target=`zenity --name=Gedit --list --title=$compiler --text="Select Target Platform" --column=Target Linux FreeBSD NetBSD OpenBSD Solaris Darwin iPhone_Simulator 2> /dev/null `
case $target in
	Linux) t=linux;;
	Darwin) t=darwin;;
	FreeBSD) t=freebsd;;
	NetBSD) t=netbsd;;
	OpenBSD) t=openbsd;;
	iPhone_Simulator) t=iphonesim;;
	Solaris) t=solaris;;
	*) t=linux;;
esac
if [ $? -ne 0 ];then
	echo "Compilation is cancelled by $USER"> /dev/stderr
	exit 1
fi
cc=$compiler
arg="-T$t -Fi\"$GEDIT_CURRENT_DOCUMENT_DIR\" -Fl\"$GEDIT_CURRENT_DOCUMENT_DIR\"  $arg"
ext=elf
echo -e "Target=$target:amd64\nCompiler=$cc\nExtention=$ext\nLanguage=$lang\nDocName=$name\nDocExt=$dext"
target="$t.amd64"
if [ -d "./$name.$target" ];then
	cp "$GEDIT_CURRENT_DOCUMENT_NAME" "./$name.$target/$name.$dext"
else
	mkdir $name.$target
	cp "$GEDIT_CURRENT_DOCUMENT_NAME" "./$name.$target/$name.$dext"
fi
arg="$(zenity --name=Gedit --entry --title="$cc" --text='Any extra argument?\n*use oniy if sugested after 1st Compile*' 2> /dev/null) $arg"
$cc $arg "$GEDIT_CURRENT_DOCUMENT_NAME"
if [ "$?" != 0 ];then
	err=$?
	echo -e "Resolve the errors" &> /dev/stderr
	cd "$GEDIT_CURRENT_DOCUMENT_DIR"
	zenity --name=Gedit --error --title="$cc" --text="compilation of $GEDIT_CURRENT_DOCUMENT_NAME failed for errors" 2> /dev/null
	rm -rf "$name.$target" 2> /dev/null
	exit $err
else
	cd "$name.$target"
	$cc $arg -a -al -an -ar -at -Aas "$name.$dext" &> /dev/null
	clear 2> /dev/null
	cd ..
	mv $name z.$name.$target.$ext
	tar -cf "z.$name.$target.tar" "$name.$target" 2> /dev/null
	rm -f "z.$name.$target.tgz" &> /dev/null
	gzip "z.$name.$target.tar" 2> /dev/null
	mv ./z.$name.$target.tar.gz ./z.$name.$target.tgz 2> /dev/null
	rm -rf "$name.$target"
	rm $name.o
	exit 0 2>/dev/null
fi
