#!/bin/sh
# [Gedit Tool]
# Name=Format
# Languages=python,python3
# Input=document
# Output=replace-document
# Applicability=titled
# Save-files=nothing
# Shortcut=<Shift>F1

if type -p autopep8; then
	autopep8 -
else
	echo autopep8 not installed 1>&2
fi
