#!/bin/sh
# [Gedit Tool]
# Name=Lint
# Languages=python,python3
# Input=nothing
# Output=output-panel
# Applicability=local
# Save-files=document
# Shortcut=F6

root=$(git rev-parse --show-toplevel 2> /dev/null)
if [ "$root" ]; then
	cd "$root"
fi
if poetry check > /dev/null 2>&1; then
	poetry run pylint "$GEDIT_CURRENT_DOCUMENT_DIR/$GEDIT_CURRENT_DOCUMENT_NAME"
else
	pylint "$GEDIT_CURRENT_DOCUMENT_DIR/$GEDIT_CURRENT_DOCUMENT_NAME"
fi
