#!/bin/bash
# [Gedit Tool]
# Input=nothing
# Save-files=document
# Output=output-panel
# Shortcut=F3
# Applicability=titled
# Languages=python,python3
# Name=Check

v=${GEDIT_CURRENT_DOCUMENT_TYPE#*-}
pyflakes "$GEDIT_CURRENT_DOCUMENT_NAME"
