#!/bin/bash
# [Gedit Tool]
# Input=nothing
# Save-files=document
# Output=output-panel
# Shortcut=F3
# Applicability=all
# Languages=python,python3
# Name=Validate Code......

v=${GEDIT_CURRENT_DOCUMENT_TYPE#*-}
if [ "$v"!="" ];then
	if [ "$v"=="Python2K" ];then
		python -d $GEDIT_CURRENT_DOCUMENT_NAME
	else
		python3 -d $GEDIT_CURRENT_DOCUMENT_NAME
	fi
else
	python3 -d $GEDIT_CURRENT_DOCUMENT_NAME
fi
