#!/bin/zsh
if [[ ! -f "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/recompile.lck" ]];then
	${ZDOTDIR:-$HOME/.zsh}/ztasklocked recompile $fpath ${(v)zsh_loaded_plugins} &!
else
	printf 'zsh: zrecompile running...\n'
fi
