#!/bin/sh
if command -v git-lfs > /dev/null 2>&1; then
	git lfs pre-push "$@"
else
	echo "E:This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS set pre-push.git-lfs=false"
fi
