[options]
Include = /etc/paru.conf

SudoLoop
CleanAfter
PgpFetch
CombinedUpgrade
BatchInstall
SaveChanges
BottomUp
CleanAfter
InstallDebug
BatchInstall
NoCheck

LocalRepo = paru
Chroot = /var/lib/aurbuild/x86_64

[bin]
GitFlags = -c http.version=HTTP/1.1
ChrootFlags = -D /run/clamav -D /run/user/1000/gnupg -D /home/ahm/.gnupg
