#!/bin/bash -e
# HOOK-CONDITION: [[ $(git remote get-url origin) =~ ^ssh://aur@aur.archlinux.org/ ]]
if grep -q 'git://|git+http' PKGBUILD;then
	makepkg -o
fi
echo "info:Updating SRCINFO"
makepkg --printsrcinfo > .SRCINFO
git add .SRCINFO
