#!/bin/bash
# shellcheck disable=SC2016
FORMATTERS=(
	[sh]=shfmt
	[bash]=shfmt
	[mksh]=shfmt
	[bats]=shfmt
	[python]=autopep8
	[python3]=autopep8
	[python2]=autopep8-python2
)

format_file()
{
	case $1 in
		bash | bats | mksh) shfmt -w -i 0 -ci -sr -ln "$1" -kp -fn "$2" ;;
		sh) shfmt -w -i 0 -ci -sr -p -kp -fn "$2" ;;
		python | python3) autopep8 -i "$2" ;;
		python2) autopep8-python2 -i "$2" ;;
		*) return 1 ;;
	esac
}

IFS=$'\r\n' GLOBIGNORE='*' command eval 'STAGED=($(git diff --name-only --cached))'
for file in "${STAGED[@]}"; do
	if ! [ -e "$file" ]; then
		continue
	fi
	if [ "$(head -c2 "$file")" = "#!" ]; then
		intrprtr=$(
			head -1 "$file" |
				tr ' ' '\n' |
				grep -Ev '^-|^(.*)=(.*)$' |
				awk '
				$1 ~ /bin\/env/	{
					enved="true";
				}; {
					intr=$0
				}; (enved == "true" && NR > 2) || NR > 1 {
					exit
				}; END {
					len=split(intr, path , "/")
					print path[len]
				};'
		)
	else
		case ${file##*.} in
			py) intrprtr=python ;;
			*) intrprtr='' ;;
		esac
	fi
	if [[ ${FORMATTERS[$intrprtr]+_} ]]; then
		if command -v "${FORMATTERS[$intrprtr]}" &> /dev/null; then
			echo "I:[${intrprtr^^}] Formatting $file"
			format_file "$intrprtr" "$file" 2> /dev/null
			git add "$file"
		else
			echo "W:Formatter for $intrprtr [${FORMATTERS[$intrprtr]}] is not installed."
			unset "FORMATTERS[$intrprtr]"
		fi
	fi
done
