#!/bin/bash
# shellcheck disable=SC2016
FORMATTERS=(
	[sh]=shfmt
	[bash]=shfmt
	[mksh]=shfmt
	[bats]=shfmt
)

format_file() {
	case $1 in
		(bash|bats|mksh) shfmt -w -s -i 0 -ci -sr -ln "$1" -kp -fn "$2";;
		(sh) shfmt -w -s -i 0 -ci -sr -ln posix -kp -fn "$2";;
		(*) return 1;;
	esac
}
IFS=$'\r\n' GLOBIGNORE='*' command eval 'STAGED=($(git diff --name-only --cached))'
for file in "${STAGED[@]}"; do
	if [ "$(head -c2 "$file")" = "#!" ]; then
		intrprtr=$(
			head -1 '/home/mubashshir/Documents/git/anime-scripts/danime/00header' |
				tr ' ' '\n' |
				grep -Ev '^-|^(.*)=(.*)$' |
				awk '$1 ~ /bin\/env/ { enved="true" }
				{intr=$0;}
				(enved == "true" && NR > 2) || NR > 1 {exit;}
				END{len=split(itr, path , "/");print path[len]}'
		)
	fi
	if [[ ${FORMATTERS[$intrprtr]+_}  ]];then
		if command -v "${FORMATTERS[$intrprtr]}" &>/dev/null;then
			echo "I:[${intrprtr//a-z/A-Z}] Formatting $file"
			format_file "$intrprtr" "$file" 2>/dev/null
			git add "$file"
		else
			echo "W:Formatter for $intrprtr [${FORMATTERS[$intrprtr]}] is not installed."
			unset "FORMATTERS[$intrprtr]"
		fi
	fi
done
