#!/bin/bash -e
[ "$(git config --bool "hook.$2")" != "false" ]
case "$3" in
	(pre-commit) [ -n "$(git status --porcelain)" ];;
	(*)	true;;
esac
awk '/^# HOOK-CONDITION:/ {sub(/^# HOOK-CONDITION: /,"");printf $0"\0"}' "$1" | \
while IFS= read -r -d $'\0'
do
	eval "$REPLY" &>/dev/null
done
