players:
    mpv:
        poll_interval: 0.5
    monitored:
    - mpv
fileinfo:
    exclude_patterns:
    - "/mnt/Multimedia/\\.*/.*"
    whitelist:
    - /mnt/Multimedia
    - /mnt/Torrents
version: '1.0'
