players:
    mpv:
        poll_interval: 0.5
    monitored: [mpv]
fileinfo:
    whitelist:
    - /mnt/Multimedia/Anime
    - /mnt/Multimedia/Animation
    - /mnt/Multimedia/Movie
    - /mnt/Torrents
version: '1.0'
