#!/bin/zsh
() {
	if ! zplug defer;then
		git -C "$1" submodule init --quiet plugins omz
		if ! git -C "$1" submodule update --progress plugins omz
		then
			printf "zsh: failed to initialize plugins\n"
			function zsh-defer {
				while [[ $1 =~ ^[+-] ]];do shift; done
				"$@"
			}
		else
			printf "zsh: finished cloning modules\n"
			zplug defer
		fi
	else
		"$ZDOTDIR/ztasklocked" exec \
			git -C "${___plugins[1]}" submodule update --progress "${___plugins[@]:1}" &!
	fi
} "${${ZDOTDIR/%//.zshrc}:P:h}" <&- # close input stream
