#!/bin/zsh
#zplug async
zplug hacker-quotes
zplug-defer bd
zplug-defer lazyload
zplug-defer completions
zplug-defer auto-notify
zplug-defer systemd
#zplug-defer fzf-tab
zplug-defer fast-syntax-highlighting
zplug-defer autosuggestions
zplug-defer autopair
zplug-defer you-should-use
zplug-defer bash-completions-fallback
zplug-defer zshmarks
zplug-defer history-substring-search
zplug-defer command-time
zplug-defer mask
#zplug auto-ls
zplug-defer autoswitch_virtualenv
zplug-defer rockz
zplug-defer zinsults
zplug-defer git
zplug-defer forgit
zplug-defer archlinux
zplug-defer dotenv
zplug-defer rbenv
zplug-defer z
[[ -x /usr/bin/nix ]] && {
	zplug-defer nix
	zplug-defer nix-shell
}

if [[ $ENV[color_prompt] == yes ]]; then
	zplug-defer gitstatus-async
	zplug-defer devprompt
#	zplug-defer gio-vfs-prompt
fi

zsh-defer +a eval '${ZDOTDIR:-$HOME/.zsh}/ztasklocked recompile $fpath ${(v)zsh_loaded_plugins}'
