#!/bin/bash
DOTFILE_DIR=$(env -u GIT_DIR git -C "${0%/*}" rev-parse --show-toplevel)
EXEC="$DOTFILE_DIR/submodules/git-secrets/git-secrets"
if [ -z "$DOTFILE_DIR" ]; then
	mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}/git/hooks
	EXEC="${XDG_CACHE_HOME:-$HOME/.cache}/git/hooks/good-commit"
	curl -s -o "$EXEC" \
		https://raw.githubusercontent.com/awslabs/git-secrets/master/git-secrets
	chmod +x "$EXEC"
elif ! [ -x "$EXEC" ]; then
	printf 'git: init && update submodules in dotfile repo.'
	exit 70
fi
exec "$EXEC" "$@"
