#!/bin/sh
# shellcheck disable=SC1087
if [ -f "$1" ]; then
	git interpret-trailers --in-place "$1"

	TS=$(git config --get trailer.separators)
	TS="${TS:-:}"
	DTS=$(echo "$TS" | cut -c1)

	git interpret-trailers --parse --trim-empty "$1" |
		sed "s/[$TS]\{1,\}/$DTS/" | sort -u |
		while IFS="$TS" read -r trailer arg; do
			token=$(
				git config --get-regexp 'trailer.*.key' |
					awk -F. '$3 ~ /^key '"$trailer"'/{print $2}'
			)
			generator=$(git config --get "trailer.$token.generator")
			key=$(git config --get "trailer.$token.key")
			if [ -n "$generator" ]; then
				rep=$(
					sh -c "$generator"' "$1" 2>/dev/null || echo "$1"' -- "$arg" |
						sed -e 's/^[[:blank:]]*//' \
							-e 's/[[:blank:]]*$//' \
							-e '/^$/d'
				)
			fi
			if ! echo "$key" | grep -q "[$TS]$"; then
				key="$key$DTS "
			fi
			sed -Ei "/^$trailer[$TS]+$(echo "$arg" | sed 's@/@\\/@g')$/c\\$key${rep:-$arg}" "$1"
			unset token rep generator key
		done
fi
