#!/bin/bash
# [Gedit Tool]
# Input=nothing
# Output=output-panel
# Shortcut=<Shift>F1
# Applicability=titled
# Save-files=document
# Languages=c,cpp,java
# Name=Compile...

get_avr()
{
	local key val i
	key="${1%%=*}"
	val="${1#*=}"
	case "$key" in
		MCU | mcu)
			declare -g MCU="${val,,}"
			args+=("-mmcu=$MCU")
			;;
		FMT | fmt)
			case "$val" in
				binary | bin) val=binary ;;
				srec | srcrec) val=srec ;;
				hex | ihex | intel | *) val=ihex ;;
			esac
			declare -g FMT="$val"
			;;
		SECTION | section)
			if [[ "$key" != "$val" ]]; then
				for i in eeprom lock fuse signature sig; do
					case ":${val^^}:" in
						*:${i^^}:*) declare -gi "${i^^}=1" ;;
					esac
				done
			else
				__hint "Valid Sections: eeprom lock fuse signature/sig"
			fi
			;;
	esac
	if ((${#AVR_OUT[@]} == 0)); then
		declare -rgA AVR_OUT=(
			["ihex"]="hex"
			["binary"]="bin"
			["srec"]="srec"
		)
	fi
}

get_pkg()
{
	if pkg-config "$1"; then
		readarray -t -O "${#args[@]}" args < <(
			pkg-config --cflags --libs "$1" | tr -s ' ' '\n'
		)
	else
		__error "pkg-config: $1 not found."
	fi
}
get_file()
{
	files+=("$1")
}

HELPERS=(
	'file[files]: Add another file to compile/run with this file'
	'avr[avr-gcc]: AVR Specific arguments'
	'    (required) mcu=<microcontroller>'
	'    (optional) fmt=<bin|srec|hex>   (default: hex)'
	'    (optional) section=<eeprom|lock|fuse|sig> (default: empty)'
	'pkg[pkg-config] PKG-CONFIG cflags and ldflags'
)
FILTER=compile
## start args
source "${0%/*}/.lib/args"
## end args

case "$TYPE/${NAME##*.}" in
	x-csrc/ino) TYPE=x-arduino ;;
	x-csrc/c) grep -qxE '\s*#\s*include\s*<avr/\w+.h>' "$NAME" && TYPE="x-avr-csrc" ;;
esac
typeset -p files

case "$TYPE" in
	x-csrc) exec gcc "${files[@]}" -o "${NAME}.elf" "${args[@]}" ;;
	x-c++src) exec g++ "${files[@]}" -o "${NAME}.elf" "${args[@]}" ;;
	x-java)
		cd "$DIR" || exit 1
		exec javac "${args[@]}" "$NAME"
		;;
	x-arduino) exec arduino-cli compile "${args[@]}" --no-color "$DIR" ;;
	x-avr-csrc)
		set -e
		if [[ -z "$MCU" ]]; then
			__error "No target MCU defined"
			__hint "Add \`# avr MCU=<MCU>\` as comment."
			false
		fi

		if ! command -pv avr-gcc 2> /dev/null >&2; then
			__error "avr-gcc not installed."
			false
		fi

		avr-gcc -Wall -Os "${files[@]}" -o "$NAME.$MCU.out" "${args[@]}"
		avr-size -C "--mcu=$MCU" "$NAME.$MCU.out"
		(
			[[ "$FMT" ]] || FMT=ihex
			avr-objcopy -R .eeprom -R .fuse -R .lock -R .signature \
				-O "$FMT" "$NAME.$MCU.out" "$NAME.$MCU.${AVR_OUT["$FMT"]}"
			avr_objcopy()
			{
				avr-objcopy --no-change-warnings -j ".$1" --change-section-lma ".$1=0" \
					-O "$FMT" "$NAME.$MCU.out" "$NAME.$MCU.${2:-$1}.${AVR_OUT["$FMT"]}"
			}
			((!EEPROM)) || avr_objcopy eeprom
			((!FUSE)) || avr_objcopy fuse
			((!SIGNATURE && !SIG)) || avr_objcopy signature sig
			((!LOCK)) || avr_objcopy lock
		)
		rm -f "$NAME.$MCU.out"
		;;
	*)
		echo "Unsupported: text/${TYPE}" >&2
		exit 1
		;;
esac
