#!/bin/bash
# [Gedit Tool]
# Input=nothing
# Output=output-panel
# Shortcut=<Shift>F1
# Applicability=titled
# Save-files=document
# Languages=arduino,asm-att,asm-intel,c,cpp,gas x86-64,java,rust
# Name=Compile...

get_avr()
{
	local key val i
	key="${1%%=*}"
	val="${1#*=}"
	case "$key" in
		ELF | elf) declare -gi keep_elf=1 ;;
		CLK | clk)
			case "$val" in
				*[kMG] | *[kMG]Hz)
					key="${val%[kMG]*}"
					case "${val#"$key"}" in
						k | kHz) i=1000 ;;
						M | MHz) i=1000000 ;;
						G | GHz) i=1000000000 ;;
					esac
					case "$key" in
						[0-9]*.[0-9]*) declare -gi AVR_CLOCK=$(("${key%.*}" * i + "${key#*.}" * (i / 1000))) ;;
						[0-9]*) declare -gi AVR_CLOCK=$((key * i)) ;;
						*) __error "avr: Invalid Clock Speed: $val" ;;
					esac
					;;
				[0-9]*Hz) declare -gi AVR_CLOCK="${val%Hz}" ;;
				[0-9]*) declare -gi AVR_CLOCK="$val" ;;
				*) __error "avr: Invalid Clock Speed: $val" ;;
			esac
			;;
		OPTIMIZE | opt) declare -g AVR_OPTIMIZE="$val" ;;
		MCU | mcu)
			declare -g MCU="${val,,}"
			args+=("-mmcu=$MCU")
			;;
		FMT | fmt)
			case "$val" in
				binary | bin) val=binary ;;
				srec | srcrec) val=srec ;;
				hex | ihex | intel | *) val=ihex ;;
			esac
			declare -g FMT="$val"
			;;
		SECTION | section)
			if [[ "$key" != "$val" ]]; then
				for i in eeprom lock fuse signature sig; do
					case ":${val^^}:" in
						*:${i^^}:*) declare -gi "${i^^}=1" ;;
					esac
				done
			else
				__hint "Valid Sections: eeprom lock fuse signature/sig"
			fi
			;;
	esac
	if ((${#AVR_OUT[@]} == 0)); then
		declare -rgA AVR_OUT=(
			["ihex"]="hex"
			["binary"]="bin"
			["srec"]="srec"
		)
	fi
}

run()
{
	local exec
	if [[ $1 == exec ]]; then
		shift
		exec=exec
	fi

	echo "+ $*" >&2
	$exec "$@"
}

for_triplet()
{
	local cmd="$1" exec=''
	shift
	if [[ $cmd == exec ]]; then
		cmd="$1"
		shift
		exec=exec
	fi
	if ((STRIP_OUTPUT)) && [[ $exec == exec ]]; then
		exec=''
		set -e
	fi

	if [[ "$TARCH$TSYSTEM$TABI" ]] && hash -- "$TARCH-$TSYSTEM-$TABI-$cmd" 2> /dev/null; then
		run $exec "$TARCH-$TSYSTEM-$TABI-$cmd" "$@"
	elif [[ "$LIBC" && ":$cmd:" =~ :(gcc|clang): ]] && hash -- "$LIBC-$cmd" 2> /dev/null; then
		run $exec "$LIBC-$cmd" "$@"
	else
		[[ "$TARCH$TSYSTEM$TABI" ]] && echo "'$TARCH-$TSYSTEM-$TABI-$cmd' not found" >&2 && echo "Using '$cmd'" >&2
		run $exec "$cmd" "$@"
	fi
}

get_pkg()
{
	if for_triplet pkg-config "$1"; then
		readarray -t -O "${#args[@]}" args < <(
			for_triplet pkg-config --cflags --libs "$1" | tr -s ' ' '\n' | sed '/^$/d'
		)
	else
		__error "pkg-config: $1 not found."
	fi
}

get_libc()
{
	declare -g LIBC="$1"
}

get_triplet()
{
	[[ -z $1 ]] || read -r TARCH TSYSTEM TABI <<< "$1"

	case "$TARCH" in
		amd64)
			TARCH=x86_64
			HFTARCH=amd64
			;;
		i?86 | x86)
			TARCH=i686
			HFTARCH=i386
			;;
	esac

	case "$TSYSTEM/$TABI" in
		w64/mingw32) OUTPUT=exe ;;
	esac
}

get_output()
{
	[[ -z $1 ]] || OUTPUT="$1"
}

get_strip()
{
	[[ $1 == "false" ]] || STRIP_OUTPUT=1
	[[ $1 == "false" ]] || read -ra STRIP_ARGS <<< "$1"
}

get_local()
{
	args+=(
		-idirafter ~/.local/include
	)
}

get_file()
{
	echo '# file <path> is deprecated!' >&2
	files+=("$1")
}

arduino_get_board()
{
	arduino-cli board list --format jsonmini \
		| jq -r 'if has("detected_ports") then
		.detected_ports
	else . end
	| .['"$1"']
	| [
		"--fqbn",
		(.matching_boards | first | .fqbn),
		"--port",
		(.port | .address)
	]
	| join("\n")' \
		| tee /dev/stderr 2> >(sed -n '2s/^/@ fqbn /p;4s/^/@ port /p' >&2)
}

get_arduino()
{
	case "$1" in
		list) exec arduino-cli board list ;;
		auto) mapfile -t -O "${#args[@]}" args < <(arduino_get_board 0) ;;
		[0-9]*) mapfile -t -O "${#args[@]}" args < <(arduino_get_board "$1") ;;
	esac
}

HELPERS=(
	'arduino <arg>:     Select arduino automatically.'
	'    list: List connected boards'
	'    N:    Connect to Nth board.'
	'    auto: Select first connected board'
	'avr[avr-gcc]: AVR Specific arguments'
	'    (required) mcu=<microcontroller>'
	'    (optional) clk=<Clock Speed>[KMG](Hz)   (default: platform default)'
	'    (optional) opt=<0|1|2|3|fast|g|s>   (default: 2)'
	'    (optional) fmt=<bin|srec|hex>   (default: hex)'
	'    (optional) section=<eeprom|lock|fuse|sig> (default: empty)'
	'    (optional) elf (keep intermediate elf)'
	'pkg[pkg-config] PKG-CONFIG cflags and ldflags'
	'triplet: Specify system triplet'
	'output : Specify output extension (o implies -c, S/asm implies -S, pp.c implies -E)'
	'strip  : Strip program after compilation [pass arguments to strip with this]'
	'libc:  specify compiler for libc (known value: empty, musl)'
	'local: include local header files'
)

FILTER=compile
## start args
source "${0%/*}/.lib/args"
## end args

case "$TYPE/${NAME##*.}" in
	x-csrc/ino) TYPE=x-arduino ;;
	x-csrc/c) grep -qxE '\s*#\s*include\s*<avr/\w+.h>' "$NAME" && TYPE="x-avr-csrc" ;;
esac

ONAME="${NAME}${TARCH:+.${HFTARCH:-$TARCH}}.${OUTPUT:-elf}"
case "${OUTPUT:-elf}" in
	o | obj) args=(-c "${args[@]}") ;;
	S | asm) args=(-S "${args[@]}") ;;
	pp.c) args=(-E "${args[@]}") ;;
esac
case "$TYPE" in
	x-csrc) for_triplet exec gcc "${files[@]}" -o "${ONAME}" "${args[@]}" ;;
	x-c++src) for_triplet exec g++ "${files[@]}" -o "${ONAME}" "${args[@]}" ;;
	rust) exec rustc "${files[@]}" -o "${ONAME}" "${args[@]}" ;;
	x-java)
		cd "$DIR" || exit 1
		exec javac "${args[@]}" "$NAME"
		;;
	x-arduino) exec arduino-cli-log compile "${args[@]}" --no-color "$DIR" ;;
	x-avr-csrc)
		set -e
		if ! command -pv avr-gcc 2> /dev/null >&2; then
			__error "avr-gcc not installed."
			false
		fi

		if [[ -z "$MCU" ]]; then
			__error "No target MCU defined"
			__hint "Add \`# avr mcu=<MCU>\` as comment."
			false
		fi

		((AVR_CLOCK == 0)) || args=("-DF_CPU=${AVR_CLOCK}UL" "${args[@]}")

		run avr-gcc "${files[@]}" -o "$NAME.$MCU.${OUTPUT:-elf}" "-O${AVR_OPTIMIZE:-2}" "${args[@]}"
		case "${OUTPUT:-elf}" in
			elf) ;;
			*) exit "$?" ;;
		esac

		avr-size -C "--mcu=$MCU" "$NAME.$MCU.elf"
		(
			[[ "$FMT" ]] || FMT=ihex
			avr_firmware()
			{
				local file="$1" fmt="$2"
				avr-objcopy -R .eeprom -R .fuse -R .lock -R .signature \
					-O "$fmt" "$file.elf" "$file.${AVR_OUT["$fmt"]}"
			}

			avr_config()
			{
				local section="${1%:*}" file="$2" fmt="$3"
				avr-objcopy --no-change-warnings -j ".$section" --change-section-lma ".$section=0" \
					-O "$fmt" "$file.elf" "$file.${section##*:}.${AVR_OUT["$FMT"]}"
			}

			run avr_firmware "$NAME.$MCU" "$FMT"
			((!EEPROM)) || run avr_config eeprom "$NAME.$MCU" "$FMT"
			((!FUSE)) || run avr_config fuse "$NAME.$MCU" "$FMT"
			((!SIGNATURE && !SIG)) || run avr_config signature:sig "$NAME.$MCU" "$FMT"
			((!LOCK)) || run avr_config lock "$NAME.$MCU" "$FMT"
		)
		((keep_elf)) || rm -f "$NAME.$MCU.elf"
		;;
	*)
		echo "Unsupported: text/${TYPE}" >&2
		exit 1
		;;
esac

if ((STRIP_OUTPUT)) && [[ $TYPE =~ ^x-c(|\+\+)src$ ]]; then
	unset STRIP_OUTPUT
	for_triplet exec strip "${STRIP_ARGS[@]}" "${ONAME}"
fi
