#!/bin/bash
# [Gedit Tool]
# Shortcut=<Shift>F2
# Output=output-panel
# Languages=c
# Input=nothing
# Name=Debug
# Save-files=nothing
# Applicability=all
FILTER=debug
get_arduino()
{
	case "$1" in
		list) exec arduino-cli board list ;;
		auto) mapfile -t -O "${#args[@]}" args < <(
			arduino-cli board list --format jsonmini \
				| jq -r 'first
			| [
				"--fqbn",
				(.matching_boards | first | .fqbn),
				"--port",
				(.port | .address)
			]
			| join("\n")' \
				| tee /dev/stderr 2> >(sed -n '2s/^/@ fqbn /p;4s/^/@ port /p' >&2)
		) ;;
		[0-9]*) mapfile -t -O "${#args[@]}" args < <(
			arduino-cli board list --format jsonmini \
				| jq -r '.['"$1"']
			| [
				"--fqbn",
				(.matching_boards | first | .fqbn),
				"--port",
				(.port | .address)
			]
			| join("\n")'
		) ;;
	esac
}
HELPERS=(
	'arduino <arg>:     Select arduino automatically.'
	'    list: List connected boards'
	'    N:    Connect to Nth board.'
	'    auto: Select first connected board'
)
## start args
source "${0%/*}/.lib/args"
## end args
case "$TYPE/${NAME##*.}" in
	x-csrc/ino) TYPE=x-arduino ;;
	x-csrc/c) grep -qxE '\s*#\s*include\s*<avr/\w+.h>' "$NAME" && TYPE="x-avr-csrc" ;;
esac

TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)
cat > "$TMPFILE" << EOF
command -p printf '\033]2;Debug: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
EOF

case "$TYPE" in
	x-java)
		echo "exec jdb \"${GEDIT_CURRENT_DOCUMENT_NAME%.*}\""
		;;
	x-arduino)
		printf 'exec arduino-cli monitor'
		printf ' %q' "${args[@]}"
		echo
		;;
	*)
		echo "set \"\$@\" \"./$GEDIT_CURRENT_DOCUMENT_NAME.elf\""
		echo "! [[ -f core ]] || set \"\$@\" core"
		echo 'exec cgdb "$@"'
		;;
esac >> "$TMPFILE"

chmod +x "$TMPFILE"
exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null
