#!/bin/bash
# [Gedit Tool]
# Shortcut=<Shift>F2
# Output=output-panel
# Languages=c
# Input=nothing
# Name=Debug
# Save-files=nothing
# Applicability=all

dext=${GEDIT_CURRENT_DOCUMENT_NAME##*.}
name=${GEDIT_CURRENT_DOCUMENT_NAME%.*}
case $dext in
	[c,C]) lang=C ;;
	[c,C][p,P,x,X][p,P,x,X]) lang=C++ ;;
	[j,J][a,A][v,V][a,A]) lang=Java ;;
	*) cc=gdb ;;
esac

if [ "$lang" = Java ]; then
	cd "$GEDIT_CURRENT_DOCUMENT_DIR"
	arg=$(zenity --entry --title="Compile..." --text="Any argument to debug?\n*Optional*\n seperate each with \"- \"" --entry-text="" 2> /dev/null)
	clear
	javac $GEDIT_CURRENT_DOCUMENT_NAME
	exo-open --launch TerminalEmulator jdb ${GEDIT_CURRENT_DOCUMENT_NAME%.*} $arg
else

	TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)

	cat > "$TMPFILE" << EOF
#!/bin/bash
printf '\e]2;Debug: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
set "\$@" "./$GEDIT_CURRENT_DOCUMENT_NAME.elf"
if [[ -f core ]];then
set "\$@" core
fi
exec cgdb "\$@"
EOF

	chmod +x "$TMPFILE"

	exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null

fi
