#!/bin/bash
# [Gedit Tool]
# Name=Run......
# Applicability=local
# Languages=c,cpp,pascal
# Save-files=nothing
# Output=nothing
# Shortcut=F5
# Input=nothing

dext="${GEDIT_CURRENT_DOCUMENT_NAME##*.}"
TARGET="z.$(sed -e s/.${dext}$// <<< "$GEDIT_CURRENT_DOCUMENT_NAME").amd64.elf"
TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)

cat > "$TMPFILE" <<EOF
#!/bin/sh
printf '\e]2;Run: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
TIMEFORMAT=\$'\n========\n                      elapsed %3R'
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
time "./$TARGET"
printf '\033[A\rProcess returned %d,\n' "\$?"
read -rsp$'Press RETURN to continue...'
EOF

chmod +x "$TMPFILE"
cd "$GEDIT_CURRENT_DOCUMENT_DIR"

exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null
