#!/bin/env python3
# [Gedit Tool]
# Name=Format
# Input=selection-document
# Output=replace-selection
# Applicability=titled
# Save-files=document
# Languages=html
# Shortcut=F3

import sys
from bs4 import BeautifulSoup
text = sys.stdin.read()
soup = BeautifulSoup(text, features="lxml")
print(soup.prettify())
