#!/bin/bash
# [Gedit Tool]
# Name=Run...
# Languages=java
# Save-files=document
# Applicability=titled
# Shortcut=F5
# Input=document
# Output=output-panel

FILTER=run
declare -ga stdin rargs

get_stdin()
{
	stdin+=("$1")
}
get_arg()
{
	rargs+=("$1")
}
HELPERS=(
	'stdin <line>: write line to program stdin'
	'arg <arg>: pass arg to program'
)

## start args
source "${0%/*}/.lib/args"
## end args

TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)
cat > "$TMPFILE" << EOF
#!/bin/bash
$(declare -p stdin)
$(declare -p args)
$(declare -p rargs)
command -p printf '\e]2;Run: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
TIME_FORMAT=\$(cat <<EOT


========
Consumed %KkB
Process returned %x
Elapsed %e (%U user, %S system; %P% CPU)
EOT
)
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
unset _JAVA_OPTIONS
$(((${#stdin[@]} == 0)) || echo "printf '> %s\\n' \"\${stdin[@]}\" | tee /dev/stderr | cut -c3- | \\")
/bin/time \
	-f "\$TIME_FORMAT" \
	-- \
	java -cp "$GEDIT_CURRENT_DOCUMENT_DIR" "\${args[@]}" "$(echo "$GEDIT_CURRENT_DOCUMENT_NAME" | sed -e s/.java$//)" "\${rargs[@]}"
read -rsp$'Press RETURN to continue...'
EOF

chmod +x "$TMPFILE"

exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null
