#!/bin/sh
# [Gedit Tool]
# Name=Format
# Languages=python,python3
# Input=nothing
# Output=nothing
# Applicability=local
# Save-files=nothing
# Shortcut=<Shift>F1

if command -vp autopep8 | grep -q 'autopep8$'; then
	autopep8 --in-place "$GEDIT_CURRENT_DOCUMENT_DIR/$GEDIT_CURRENT_DOCUMENT_NAME"
else
	echo autopep8 not installed 1>&2
fi
