#!/bin/bash
# [Gedit Tool]
# Input=document
# Shortcut=F5
# Languages=python,python3
# Save-files=document
# Name=Run
# Applicability=all
# Output=output-panel

v=${GEDIT_CURRENT_DOCUMENT_TYPE#*-}
intrp=python

if [ "$v" == "python" ]; then
	intrp=python3
fi
TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)

cat > "$TMPFILE" << EOF
#!/bin/bash
printf '\e]2;Run: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
TIMEFORMAT=\$'\n========\n                      elapsed %3R'
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
time "$intrp" "./$GEDIT_CURRENT_DOCUMENT_NAME"
printf '\033[A\rProcess returned %d,\n' "\$?"
read -rsp$'Press RETURN to continue...'
EOF

chmod +x "$TMPFILE"
cd "$GEDIT_CURRENT_DOCUMENT_DIR"

exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null
