#!/bin/bash
# [Gedit Tool]
# Name=Compile
# Languages=vala
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=document
# Shortcut=<Shift>F1

## start args
FILTER=compile
source "${0%/*}/.lib/args"
## end args

valac --Xcc=-w "${files[@]}" "${args[@]}" -o "$GEDIT_CURRENT_DOCUMENT_NAME.elf"
