#!/bin/bash
# [Gedit Tool]
# Name=Compile
# Languages=vala
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=document
# Shortcut=F4

FILTER=compile
## start args
source "${0%/*}/.lib/args"
## end args

valac --Xcc=-w "$GEDIT_CURRENT_DOCUMENT_NAME" "${args[@]}" -o "$GEDIT_CURRENT_DOCUMENT_NAME.elf"
