#!/bin/bash
#!/bin/bash
# [Gedit Tool]
# Name=Run...
# Languages=vala
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Shortcut=F5

FILTER=run
## start args
source "${0%/*}/.lib/args"
## end args

TMPFILE=$(mktemp /tmp/run.gedit.XXXXXXXXXXXXX.sh)

cat > "$TMPFILE" << EOF
#!/bin/bash
printf '\e]2;Run: %s\a' "$GEDIT_CURRENT_DOCUMENT_NAME"
rm -f "$TMPFILE"
TIMEFORMAT=\$'\n========\n                      elapsed %3R'
cd "$GEDIT_CURRENT_DOCUMENT_DIR"
time "./$GEDIT_CURRENT_DOCUMENT_NAME.elf" "${args[@]}"
printf '\033[A\rProcess returned %d,\n' "\$?"
read -rsp$'Press RETURN to continue...'
EOF

chmod +x "$TMPFILE"
cd "$GEDIT_CURRENT_DOCUMENT_DIR"

exo-open --launch TerminalEmulator "$TMPFILE" &> /dev/null
