#!/bin/zsh
set -x
local LESS_TERMCAP_mb LESS_TERMCAP_md LESS_TERMCAP_me LESS_TERMCAP_so LESS_TERMCAP_se LESS_TERMCAP_us LESS_TERMCAP_ue
(
	unfunction less
	export LESS_TERMCAP_mb=$'\E[1;31m'      # begin bold 
	export LESS_TERMCAP_md=$'\E[1;36m'      # begin blink
	export LESS_TERMCAP_me=$'\E[0m'         # reset bold/blink
	export LESS_TERMCAP_so=$'\E[01;44;33m'  # begin reverse video
	export LESS_TERMCAP_se=$'\E[0m'         # reset reverse video
	export LESS_TERMCAP_us=$'\E[1;32m'      # begin underline
	export LESS_TERMCAP_ue=$'\E[0m'
	less "$@"
)
