#!/bin/bash
# HOOK-NOPIPE
DOTFILE_DIR=$(env -u GIT_DIR git -C "${0%/*}" rev-parse --show-toplevel)
GOODCOMMIT="$DOTFILE_DIR/submodules/git-good-commit/hook.sh"
if [ -z "$DOTFILE_DIR" ]; then
	mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}/git/hooks
	GOODCOMMIT="${XDG_CACHE_HOME:-$HOME/.cache}/git/hooks/good-commit"
	curl -s -o "$GOODCOMMIT" \
		https://raw.githubusercontent.com/tommarshall/git-good-commit/master/hook.sh
	chmod +x "$GOODCOMMIT"
elif ! [ -x "$DOTFILE_DIR/submodules/git-good-commit/hook.sh" ]; then
	printf 'git: init && update submodules in dotfile repo.'
	exit 70
fi
exec "$GOODCOMMIT" "$@"
