#!/bin/zsh
if [ -e ~/zprof ] || [ -p ~/pipe:zsh ];then
	zmodload zsh/datetime
	setopt PROMPT_SUBST
	PS4='+$EPOCHREALTIME %N:%i> '
	if [ -p ~/pipe:zsh ];then
		logfile=~/pipe:zsh
	else
		logfile=$(mktemp /tmp/zsh_profile.XXXXXXXX)
	fi
	echo "Logging to $logfile"
	exec 3>&2 2>$logfile
	setopt XTRACE
fi
# source
source ~/.config/shell/import
## options
zsh_options=(
	extended_glob prompt_subst rematchpcre beep
	no_nomatch null_glob c_bases no_flow_control
	auto_continue auto_cd auto_pushd pushd_silent
	pushd_to_home pushd_ignore_dups pushd_minus
	auto_list glob_complete list_packed
)
setopt $zsh_options
unset zsh_options
bindkey -e

## Lazy load section
autoload -Uz add-zsh-hook compinit
autoload -Uz "${ZDOTDIR:-$HOME/.zsh}/functions"/^_*~*.zwc(-.:t) >&3 2>&1

load rc plugins/hooks plugins/init
zplug --path "$ZDOTDIR/omz/plugins"

typeset -A ENV # base config variable
load rc completion keymap history modules \
		prompt prompt/transient plugins <&- # close input

if [ -e zprof ];then
	unsetopt XTRACE
	exec 2>&3 3>&-
	exec 2>/dev/stderr 3>/dev/null
fi
