#!/bin/zsh
setopt extended_glob
if ! [[ -f /etc/zsh/zprofile ]] || ! grep -q 'source /etc/profile' /etc/zsh/zprofile;then
	emulate sh -c 'builtin source /etc/profile'
fi

if [[ -f ~/.profile ]];then
	emulate sh -c 'builtin source ~/.profile'
fi
