#!/bin/bash -e
# HOOK-CONDITION: git status --porcelain=v1 --untracked-files=no | grep -q '/PKGBUILD$'
git diff -z --cached --name-only --diff-filter=AM '**/PKGBUILD' \
	| awk -v RS='\0' -F '/' '
		$1 !~ /D/ && $NF ~ /^PKGBUILD$/ {
			if(NF>1) {
				for(i=1; i<NF-1; i++) {
					printf "%s/", $(i)
				}
				print $(NF-1)
			} else print "."
		}' \
	| while read -r path; do
		"${0%/*}/aur" DIR "$path"
	done
