#!/bin/bash -e
# HOOK-CONDITION: [[ $(git remote get-url origin) =~ ^ssh://aur@aur.archlinux.org/ ]]
if [[ $1 = DIR ]] && [[ -d $2 ]]; then
	cd "$2"
	echo ":: Updating $2"
fi

if grep -q 'git://|git+http' PKGBUILD; then
	makepkg -o
fi
echo ":: Updating SRCINFO"
makepkg --verifysource -f \
	&& makepkg --printsrcinfo > .SRCINFO
git add -f .SRCINFO

IFS=$'\r\n' readarray -t STAGED < <(
	git diff --name-only --cached \
		| awk -F/ '{print $NF}'
)

if [ ! -f .gitignore ]; then
	echo " -> Initializing gitignore"
	echo '*' > .gitignore
else
	echo " -> Updating gitignore"
fi
for n in "${STAGED[@]}"; do
	grep -q "$n$" .gitignore && continue
	echo '!'"$n" >> .gitignore
done
grep '^!' .gitignore | cut -c2- | while read -r line; do
	if ! {
		[ -f "$line" ] || [ "$line" = "*" ]
	}; then
		sed -i "/^\!$line$/d" .gitignore
	fi
done
git add --force .gitignore

if [[ -x /usr/bin/namcap ]]; then
	namcap -im PKGBUILD
fi
