#!/bin/bash -e
if grep -q 'git://|git+http' PKGBUILD; then
	makepkg -o
fi
echo "I:Updating SRCINFO"
makepkg --verifysource -f \
	&& makepkg --printsrcinfo > .SRCINFO
git add -f .SRCINFO

IFS=$'\r\n' GLOBIGNORE='*' command eval 'STAGED=($(git diff --name-only --cached))'
git reset -q
if [ ! -f .gitignore ]; then
	echo "I:Initializing gitignore"
	echo '*' > .gitignore
else
	echo "I:Updating gitignore"
fi
for n in "${STAGED[@]}"; do
	grep -q "$n$" .gitignore && continue
	echo '!'"$n" >> .gitignore
done
grep '^!' .gitignore | cut -c2- | while read -r line; do
	if ! {
		[   -f "$line" ] || [ "$line" = "*" ]
	}; then
		sed -i "/^\!$line$/d" .gitignore
	fi
done
git add --force .gitignore
for n in "${STAGED[@]}"; do
	git add --force "$n"
done
