#!/bin/sh
exec /usr/bin/clamscan --exclude-dir=/home/mubashshir/.clamtk/viruses --exclude-dir=smb4k --exclude-dir=/run/user/mubashshir/gvfs --exclude-dir=/home/mubashshir/.gvfs --exclude-dir=.thunderbird --exclude-dir=.mozilla-thunderbird --exclude-dir=.evolution --exclude-dir=Mail --exclude-dir=kmail -i -r /home/mubashshir --log="$HOME/.clamtk/history/$(date +\%b-\%d-\%Y).log"
