#!/bin/bash
# HOOK-CONDITION: [[ ! $(git remote get-url origin) =~ ^(https?://|ssh://aur@)aur.archlinux.org/ ]]
if [[ -f "${1}~" ]]; then
	if (($(sed '/^#/d;/^$/d' < "$1" | wc -l) > 0)); then
		mv "${1}~" "${1}"
	else
		rm -f "${1}~"
	fi
fi
