#!/bin/sh
if [ -f ~/.config/shell/environment ]; then
	. ~/.config/shell/environment
fi

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
ibus-daemon -drx --panel ~/bin/ibus-ui-appindicator
dbus-update-activation-environment --all --systemd

if command -pv xcape > /dev/null 2>&1; then
	awk '{if(NR>1) printf ";";if(length($0) > 1)printf "%s", $0} END{print ""}' "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xcape.rc" |
		xcape -e "$(cat)"
fi

if [ "$XDG_SESSION_DESKTOP" = "plasma" ]; then
	unset QT_AUTO_SCREEN_SCALE_FACTOR QT_SCALE_FACTOR QT_QPA_PLATFORMTHEME
fi
systemctl_user_start()
{
	command -pv "$1" 2> /dev/null >&2 || return 0
	systemctl --user start "$1${2:+@}$2"
}

systemctl_user_start picom "$DISPLAY"

unset -f systemctl_user_start
