#!/bin/sh
if [ -f ~/.config/shell/environment ]; then
	. ~/.config/shell/environment
fi

if [ -x /usr/bin/fcitx5 ]; then
	CURRENT_IM_MODULE=fcitx
elif [ -x /usr/bin/ibus ]; then
	CURRENT_IM_MODULE=ibus
fi

if [ -n "$CURRENT_IM_MODULE" ]; then
	export "GTK_IM_MODULE=$CURRENT_IM_MODULE"
	export "QT_IM_MODULE=$CURRENT_IM_MODULE"
	export "XMODIFIERS=@im=$CURRENT_IM_MODULE"
	export "GLFW_IM_MODULE=ibus" # needed by kitty

	case "$CURRENT_IM_MODULE" in
		ibus) ibus-daemon -Rdrx --panel ~/bin/ibus-ui-appindicator ;;
		fcitx) fcitx5 -dr ;;
	esac
	dbus-update-activation-environment --all --systemd
fi
path_find()
{
	command -pv "$1" > /dev/null 2>&1
}
systemctl_user_start()
{
	path_find "$1" || return 0
	systemctl --user start "$1${2:+@}$2"
}

! [ "$(xfconf-query -c xfwm4 -p /general/use_compositing)" = "false" ] || systemctl_user_start picom "${DISPLAY%.*}"

unset -f systemctl_user_start path_find
