#!/bin/sh
if [ -f ~/.config/shell/environment ]; then
	. ~/.config/shell/environment
fi

if [ -x /usr/bin/fcitx5 ]; then
	CURRENT_IM_MODULE=fcitx
elif [ -x /usr/bin/ibus ]; then
	CURRENT_IM_MODULE=ibus
fi

if [ -n "$CURRENT_IM_MODULE" ]; then
	export "GTK_IM_MODULE=$CURRENT_IM_MODULE"
	export "QT_IM_MODULE=$CURRENT_IM_MODULE"
	export "XMODIFIERS=@im=$CURRENT_IM_MODULE"
	export "GLFW_IM_MODULE=ibus" # needed by kitty

	case "$CURRENT_IM_MODULE" in
		ibus) ibus-daemon -Rdrx --panel ~/bin/ibus-ui-appindicator ;;
		fcitx) fcitx5 -dr ;;
	esac
	dbus-update-activation-environment --all --systemd
fi
if command -pv xcape > /dev/null 2>&1; then
	awk '{if(NR>1) printf ";";if(length($0) > 1)printf "%s", $0} END{print ""}' "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xcape.rc" |
		xcape -e "$(cat)"
fi

if command -pv xmodmap > /dev/null 2>&1 && test -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/default.Xmodmap"; then
	xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}/X11/default.Xmodmap"
fi

if [ "$XDG_SESSION_DESKTOP" = "plasma" ]; then
	unset QT_AUTO_SCREEN_SCALE_FACTOR QT_SCALE_FACTOR QT_QPA_PLATFORMTHEME
fi
systemctl_user_start()
{
	command -pv "$1" 2> /dev/null >&2 || return 0
	systemctl --user start "$1${2:+@}$2"
}

systemctl_user_start picom "${DISPLAY%.*}"

unset -f systemctl_user_start
