#!/bin/sh
exec \
	/usr/bin/clamscan \
	--exclude-dir=$HOME/.clamtk/viruses \
	--exclude-dir=smb4k \
	--exclude-dir=/run/user/mubashshir/gvfs \
	--exclude-dir=$HOME/.gvfs \
	--exclude-dir=.thunderbird \
	--exclude-dir=.mozilla-thunderbird \
	--exclude-dir=.evolution \
	--exclude-dir=Mail \
	--exclude-dir=kmail \
	-i -r $HOME \
	--log="$HOME/.clamtk/history/$(date +%b-%d-%Y).log"
