#!/bin/sh
#
# chmod +x this script and set it as SSH_ASKPASS.

set -euo pipefail

pinentry << EOM | grep '^D ' | sed -e 's/^D //g' | tr -d '\n' | ~/bin/urldecode
SETTITLE GIT PinEntry
SETPROMPT >>>
SETDESC ${1:-Please enter the password.}
GETPIN
EOM
