#!/bin/sh
if [ -z "$GIT_DIR" ]; then
	GIT_DIR="$(git rev-parse --git-dir 2> /dev/null)"
fi
hooks="$HOME/$(git config --get core.hooksPath 2> /dev/null | cut -d / -f2-)"
if [ -z "$hooks" ]; then
	echo No global hooks
	exit 1
else
	case "$1" in
		enable)
			shift
			id="$1"
			hook="$hooks/hooks.d/${1%%.*}/${1#*.}"
			shift
			if [ -x "$hook" ] && [ "${id%%.*}" != "on-demand" ]; then
				git config "$@" --unset "hook.$id"
			fi
			;;
		disable)
			shift
			id="$1"
			hook="$hooks/hooks.d/${1%%.*}/${1#*.}"
			shift
			if [ -x "$hook" ] && [ "${id%%.*}" != "on-demand" ]; then
				git config "$@" "hook.$id" false
			fi
			;;
		edit)
			test "$#" -eq 2 || {
				echo "Invalid number of args." 1>&2
				exit 2
			}
			mkdir -p "$hooks/hooks.d/${2%%.*}"
			exec "$EDITOR" "$hooks/hooks.d/${2%%.*}/${2#*.}"
			;;
		ls | '')
			for hookdir in "$hooks"/hooks.d/*; do
				stage="$(basename "$hookdir")"
				if [ -d "$hookdir" ]; then
					for subhook in "$hookdir"/*; do
						if [ -x "$subhook" ]; then
							echo "$stage.${subhook##*/}"
						fi
					done
				fi
			done
			;;
		run)
			shift
			type="${1%%.*}"
			name="${1#*.}"
			if [ "$name" = "$type" ] || [ "$type" == "on-demand" ]; then
				if git config --type bool core.bare 2> /dev/null >&2; then
					echo "ERROR: Running on-demand hooks on bare repo is not possible!" >&2
					exit 1
				else
					cd "$(git rev-parse --show-toplevel)"
				fi
				hook="$hooks/hooks.d/on-demand/$name"
				shift
				[ -x "$hook" ] && exec git run "$hook" "$@"
			else
				echo "ERROR: $name: not an on-demand hook." >&2
				exit 1
			fi
			;;
		exrun)
			shift
			while [ "$1" != "--" ] && [ "$1" != "--" ]; do
				export GIT_DISABLED_HOOKS="${GIT_DISABLED_HOOKS:+$GIT_DISABLED_HOOKS:}$1"
				shift
			done
			shift
			exec "$@"
			;;
		help)
			echo "git-hooks commands: ls edit enable disable exrun run"
			;;
	esac
fi
