#!/bin/sh
setxkbmap -query |
	awk  '/^options:/{
        line = $2
    } END {
        split(line ",lv3:lsgt_switch,lv3:ralt_alt", dat, ",")
        printf "\0"
        for (i in dat)
            print dat[i] | "sort -r -u | sed \"/^$/d\" | tr -s \\\\n , | sed \"s/,$//\""
    }' |
	xargs  -0n1 setxkbmap -option
