#!/bin/zsh
path=(
	~/.local/bin
	~/bin
	~/.local/share/go/bin
	$path
	/usr/lib/surfraw
)
for n in $(echo $PATH|tr ':' '\n');do
	case ":$P:" in
		*:"$n":*) continue;;
		*)
			if [ -d "$n" ];then
				P="${P:+$P:}$n"
			fi
		;;
	esac
done
export PATH="$P"
